@startuml diagrama-secuencia-iniciarcancion

actor Vista as "Usuario"
participant Reproductor
participant Strategy as "StrategyReproductor"
participant Media as "MediaVista"

Vista -> Reproductor: iniciarReproduccion()
activate Reproductor

Reproductor -> Strategy: iniciarReproduccion()
activate Strategy

Strategy -> Strategy: SeteaMomentoInicio()
Strategy -> Media: Iniciar()
activate Media
Media --> Strategy:
deactivate Media

Strategy --> Reproductor: 
deactivate Strategy

Reproductor --> Vista: 
deactivate Reproductor

@enduml