@startuml diagrama-secuencia-iniciarcanciondistribuido

actor Vista as "Usuario"
participant Reproductor
participant Strategy as "StrategyReproductor"
participant Socket
participant Servidor as "Servidor"
participant Media as "MediaVista"

Vista -> Reproductor: iniciarReproduccion()
activate Reproductor
activate Media
activate Socket
activate Servidor

Reproductor -> Strategy: iniciarReproduccion()
activate Strategy

Strategy -> Strategy: SeteaMomentoInicio()
Strategy -> Socket: iniciarReproduccion(momentoInicio)
Socket -> Servidor: iniciarReproduccion(momentoInicio)

......

Servidor -> Socket: cancionIniciada(momentoInicio)
Socket -> Strategy: cancionIniciada(momentoInicio)
Strategy -> Media: Iniciar()
@enduml
